import React, { useState, useEffect } from 'react';
import { Settings, Save, Sparkles, Shield, Bell } from 'lucide-react';
import { settingsService } from '../../services/aiService';
import { useToast } from '../../context/ToastContext';

export const SettingsPage = () => {
  const [settings, setSettings] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [aiThreshold, setAiThreshold] = useState(0.75);
  const [weeklyCap, setWeeklyCap] = useState(3);
  const [churnCutoff, setChurnCutoff] = useState(0.65);

  const toast = useToast();

  const loadSettings = async () => {
    try {
      setLoading(true);
      const res = await settingsService.getAll();
      setSettings(res || []);
      res?.forEach(cfg => {
        if (cfg.config_key === 'ai_confidence_threshold' && cfg.config_value?.min_confidence) {
          setAiThreshold(cfg.config_value.min_confidence);
        }
        if (cfg.config_key === 'weekly_frequency_cap_default' && cfg.config_value?.whatsapp) {
          setWeeklyCap(cfg.config_value.whatsapp);
        }
        if (cfg.config_key === 'high_churn_threshold' && cfg.config_value?.churn_risk_cutoff) {
          setChurnCutoff(cfg.config_value.churn_risk_cutoff);
        }
      });
    } catch (err) {
      toast.error('Settings Error', err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSettings();
  }, []);

  const handleSave = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      await settingsService.update('ai_confidence_threshold', { min_confidence: parseFloat(aiThreshold), require_human_approval: true });
      await settingsService.update('weekly_frequency_cap_default', { whatsapp: parseInt(weeklyCap, 10), email: 2, sms: 1 });
      await settingsService.update('high_churn_threshold', { churn_risk_cutoff: parseFloat(churnCutoff) });
      toast.success('Settings Saved', 'AI governance rules and frequency limits updated in PostgreSQL.');
      loadSettings();
    } catch (err) {
      toast.error('Save Error', err.message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold font-serif text-charcoal-900 flex items-center gap-2.5">
          <Settings className="w-6 h-6 text-aurum-500" />
          System Settings & AI Governance Rules
        </h2>
        <p className="text-xs text-charcoal-500 mt-1">
          Configure minimum confidence thresholds, regulatory frequency capping, and operational risk gates.
        </p>
      </div>

      {/* Settings Form */}
      <form onSubmit={handleSave} className="bg-white rounded-2xl border border-aurum-200 shadow-luxury p-6 space-y-6 max-w-2xl text-xs">
        {/* AI Confidence Threshold */}
        <div className="space-y-2">
          <label className="font-serif font-bold text-sm text-charcoal-900 flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-aurum-500" />
            Minimum AI Confidence Score Threshold
          </label>
          <p className="text-charcoal-500 leading-relaxed">
            Recommendations generated by Gemini below this confidence score will require strict secondary human review before dispatch.
          </p>
          <div className="flex items-center gap-4 pt-1">
            <input
              type="range"
              min="0.50"
              max="0.95"
              step="0.05"
              value={aiThreshold}
              onChange={(e) => setAiThreshold(e.target.value)}
              className="flex-1 accent-aurum-400 cursor-pointer"
            />
            <span className="font-bold text-sm text-charcoal-900 bg-aurum-50 border border-aurum-300 px-3 py-1 rounded-xl">
              {Math.round(aiThreshold * 100)}%
            </span>
          </div>
        </div>

        {/* Weekly Frequency Cap */}
        <div className="space-y-2 pt-4 border-t border-gray-100">
          <label className="font-serif font-bold text-sm text-charcoal-900 flex items-center gap-1.5">
            <Shield className="w-4 h-4 text-emerald-700" />
            Default Weekly Outreach Frequency Cap (WhatsApp)
          </label>
          <p className="text-charcoal-500 leading-relaxed">
            Maximum promotional messages permissible to send to a customer in any rolling 7-day window.
          </p>
          <div className="flex items-center gap-3 pt-1">
            <input
              type="number"
              min="1"
              max="7"
              value={weeklyCap}
              onChange={(e) => setWeeklyCap(e.target.value)}
              className="w-24 p-2.5 rounded-xl border border-gray-300 font-bold focus:ring-2 focus:ring-aurum-400"
            />
            <span className="text-charcoal-600 font-medium">messages per customer / week</span>
          </div>
        </div>

        {/* High Churn Risk Cutoff */}
        <div className="space-y-2 pt-4 border-t border-gray-100">
          <label className="font-serif font-bold text-sm text-charcoal-900 flex items-center gap-1.5">
            <Bell className="w-4 h-4 text-rose-600" />
            High Churn Risk Trigger Cutoff
          </label>
          <p className="text-charcoal-500 leading-relaxed">
            Threshold at which an overdue repair or frustrated interaction automatically flags a patron as 'At Risk'.
          </p>
          <div className="flex items-center gap-4 pt-1">
            <input
              type="range"
              min="0.30"
              max="0.90"
              step="0.05"
              value={churnCutoff}
              onChange={(e) => setChurnCutoff(e.target.value)}
              className="flex-1 accent-rose-500 cursor-pointer"
            />
            <span className="font-bold text-sm text-rose-800 bg-rose-50 border border-rose-200 px-3 py-1 rounded-xl">
              {Math.round(churnCutoff * 100)}%
            </span>
          </div>
        </div>

        <div className="flex justify-end pt-4 border-t border-gray-100">
          <button
            type="submit"
            disabled={saving}
            className="px-6 py-2.5 font-bold text-white bg-aurum-400 hover:bg-aurum-500 rounded-xl shadow-luxury hover:shadow-luxury-hover transition flex items-center gap-2"
          >
            <Save className="w-4 h-4" />
            {saving ? 'Saving...' : 'Save Configuration'}
          </button>
        </div>
      </form>
    </div>
  );
};
